Integrated complex_nn
splitlearning/InferenceBenchmark pull request #26
Opened 2021-08-26 15:06 UTC by john-m24

Had to restructure the framework a bit to allow complex_nn to work properly but should still run other algos fine.

2021-08-26 18:19 UTC, john-m24 commented on src/algos/complex_nn.py
> +        for k in self.k:
make this range(self.k)... my bad

2021-09-09 19:08 UTC, tremblerz requested changes

2021-09-09 19:08 UTC, tremblerz commented on src/scheduler.py
> +            self.algo.infer(data,items["pred_lbls"])
Can you make sure the `generate_challenge` is working too?

2021-09-09 19:08 UTC, tremblerz commented on src/models/model_zoo.py
> +        if config["model_name"] == "resnet20complex":
Why do we need an if here? I think the code is same for creating optimizers

2021-09-09 19:08 UTC, tremblerz commented on src/algos/simba_algo.py
> +    def infer(self,data,labels):
great!

2021-09-09 19:08 UTC, tremblerz commented on src/algos/complex_nn.py
> +        for k in self.k:
Can you do it?

2021-11-05 15:39 UTC, closed without merging